import { filterItems, percent, routeFromHash, hydrateBallots, formatDate, escapeHTML } from './app-utils.js';

const $ = selector => document.querySelector(selector);
const root = $('#content');
let data;
const partyNames = { kok:'Kansallinen Kokoomus', ps:'Perussuomalaiset', sd:'Suomen Sosialidemokraattinen Puolue', kesk:'Suomen Keskusta', vihr:'Vihreä liitto', vas:'Vasemmistoliitto', r:'Ruotsalainen kansanpuolue', kd:'Suomen Kristillisdemokraatit', liik:'Liike Nyt', sit:'Sitoutumaton' };
const e = escapeHTML;
const href = (page,id) => `#/${page}${id ? `/${encodeURIComponent(id)}` : ''}`;
const titleFor = party => partyNames[party] || String(party || 'Muu ryhmä').toUpperCase();

function resultBar(v) { const total=v.total||v.yes+v.no+v.abstain+v.absent||1; return `<div class="result" role="img" aria-label="Jaa ${v.yes}, ei ${v.no}, tyhjää ${v.abstain}, poissa ${v.absent}"><span style="width:${percent(v.yes,total)}%"></span><span style="width:${percent(v.no,total)}%"></span><span style="width:${percent(v.abstain,total)}%"></span><span style="width:${percent(v.absent,total)}%"></span></div><div class="vote-numbers"><span><b>${v.yes}</b> jaa</span><span><b>${v.no}</b> ei</span><span>${v.abstain} tyhjää</span><span>${v.absent} poissa</span></div>`; }
function header(kicker,title,lead='') { return `<div class="page-head"><div><div class="eyebrow">${e(kicker)}</div><h1>${e(title)}</h1>${lead?`<p class="lead">${e(lead)}</p>`:''}</div><div class="updated">Päivitetty ${formatDate(data.metadata.generatedAt)}</div></div>`; }
function voteRows(items) { return items.map(v=>`<tr><td class="date">${formatDate(v.date)}</td><td><a class="row-link" href="${href('votes',v.id)}">${e(v.title||v.question||'Nimetön äänestys')}</a><span class="sub">${e(v.document||`Äänestys ${v.number}`)}${v.isAmendment?' · Muutosehdotus':''}</span></td><td>${resultBar(v)}</td></tr>`).join(''); }
function memberName(m){ return `${m.firstName||''} ${m.lastName||''}`.trim() || `Edustaja ${m.id}`; }
function memberRows(items){ return items.map(m=>`<tr><td><span class="avatar">${e((m.firstName?.[0]||'')+(m.lastName?.[0]||''))}</span><a class="row-link" href="${href('members',m.id)}">${e(memberName(m))}</a><span class="sub"><span class="party-dot"></span>${e(titleFor(m.party))}</span></td><td>${m.stats?.participation??0}%<span class="sub">${m.stats?.votes??0} kirjattua ääntä</span></td><td>${m.stats?.loyalty??0}%</td><td>${m.stats?.speeches??0}</td></tr>`).join(''); }
function table(head,body){ return `<div class="table-wrap"><table><thead><tr>${head.map(h=>`<th>${e(h)}</th>`).join('')}</tr></thead><tbody>${body}</tbody></table></div>`; }
function stats(){ const c=data.metadata.counts; return `<div class="stat-strip"><div class="stat"><strong>${c.votes.toLocaleString('fi')}</strong><span>äänestystä</span></div><div class="stat"><strong>${c.members}</strong><span>äänestänyttä edustajaa</span></div><div class="stat"><strong>${c.speeches.toLocaleString('fi')}</strong><span>puheenvuoroa</span></div><div class="stat"><strong>${c.legislation.toLocaleString('fi')}</strong><span>lakiasiaa</span></div><div class="stat"><strong>${c.amendments.toLocaleString('fi')}</strong><span>muutosehdotusta</span></div></div>`; }

function overview(){ const latest=data.votes.slice(0,8); return `<div class="page"><section class="hero"><div><div class="eyebrow">Suomen eduskunta · avoin data</div><h1>Miten sinun edustajasi toimii?</h1><p class="lead">Seuraa äänestyksiä, puheenvuoroja, ryhmälinjoja ja lakiasioiden etenemistä 2.4.2023 alkaen.</p></div><div class="hero-side"><strong>${data.metadata.counts.ballots.toLocaleString('fi')}</strong><span>yksittäistä kansanedustajan äänimerkintää seurannassa</span></div></section>${stats()}<section class="section"><div class="section-head"><h2>Uusimmat äänestykset</h2><a href="#/votes">Näytä kaikki →</a></div>${table(['Päivä','Asia','Tulos'],voteRows(latest))}</section><section class="section"><div class="section-head"><h2>Puolueet</h2><a href="#/parties">Vertaile puolueita →</a></div><div class="cards">${data.parties.slice(0,9).map(p=>`<a class="card" href="${href('parties',p.code)}"><span class="pill"><span class="party-dot"></span>${e(p.code.toUpperCase())}</span><div class="big">${p.stats.participation}%</div><p>${e(titleFor(p.code))}<br>osallistuminen nimettyihin äänestyksiin</p></a>`).join('')}</div></section></div>`; }
function listPage(page,title,lead,items,heads,rows,placeholder='Hae…'){ return `<div class="page">${header('Eduskunta-vahti',title,lead)}<div class="filters"><input data-filter placeholder="${e(placeholder)}" aria-label="Suodata luetteloa"></div><div data-list>${items.length?table(heads,rows(items)):'<div class="empty">Ei tietoja.</div>'}</div></div>`; }
function votes(id){ if(id) return voteDetail(id); const render=items=>voteRows(items); root.innerHTML=listPage('votes','Äänestykset','Kaikki nimetyt täysistuntoäänestykset huhtikuusta 2023 alkaen.',data.votes,['Päivä','Asia','Tulos'],render,'Hae aiheella tai asiakirjatunnuksella…'); bindFilter(data.votes, ['title','question','document'], ['Päivä','Asia','Tulos'], render); }
function voteDetail(id){ const v=data.votes.find(x=>x.id===id); if(!v)return notFound(); const ballots=data.ballots.filter(b=>b.voteId===id); const groups=Object.entries(Object.groupBy(ballots,b=>b.party)).sort((a,b)=>b[1].length-a[1].length); return `<div class="page">${header(`Äänestys ${v.number} · ${formatDate(v.date)}`,v.title||v.question)}<div class="detail-grid"><div><h2>Tulos</h2><div style="margin:1rem 0 2rem">${resultBar(v)}</div><p>${e(v.question)}</p>${v.detail?`<p class="lead">${e(v.detail)}</p>`:''}<section class="section"><h2>Äänet puolueittain</h2><div class="cards" style="margin-top:1rem">${groups.map(([party,bs])=>{const c={yes:0,no:0,abstain:0,absent:0,total:bs.length};bs.forEach(b=>c[b.choice]=(c[b.choice]||0)+1);return `<div class="card"><strong>${e(titleFor(party))}</strong><div style="margin-top:1rem">${resultBar(c)}</div><p>${bs.map(b=>`${e(memberName(b))}: ${e(b.choice)}`).join('<br>')}</p></div>`}).join('')}</div></section></div><aside class="aside"><h3>Taustatiedot</h3><dl><dt>Käsittelyvaihe</dt><dd>${e(v.stage||'—')}</dd><dt>Valtiopäiväasia</dt><dd>${v.documentUrl?`<a href="${e(v.documentUrl)}" target="_blank">${e(v.document)} ↗</a>`:e(v.document||'—')}</dd><dt>Pöytäkirja</dt><dd>${v.minutesUrl?`<a href="${e(v.minutesUrl)}" target="_blank">${e(v.minutes)} ↗</a>`:e(v.minutes||'—')}</dd><dt>Tulos</dt><dd>Jaa ${v.yes} · Ei ${v.no} · Tyhjää ${v.abstain} · Poissa ${v.absent}</dd></dl></aside></div></div>`; }
function members(id){ const enriched=data.members.map(m=>({...m,stats:m.stats||memberStats(m.id)})); if(id)return memberDetail(enriched.find(m=>m.id===id)); const render=items=>memberRows(items); root.innerHTML=listPage('members','Kansanedustajat','Tutki osallistumista, ryhmälinjan seuraamista ja puheenvuoroja.',enriched,['Edustaja','Osallistuminen','Ryhmälinja','Puheet'],render,'Hae nimellä tai puolueella…'); bindFilter(enriched,['firstName','lastName','party'],['Edustaja','Osallistuminen','Ryhmälinja','Puheet'],render); }
function memberStats(id){ const bs=data.ballots.filter(b=>b.mpId===id), cast=bs.filter(b=>b.choice!=='absent'), s={votes:bs.length,yes:0,no:0,abstain:0,absent:0,speeches:data.speeches.filter(x=>x.mpId===id).length,loyalty:0};bs.forEach(b=>s[b.choice]=(s[b.choice]||0)+1);s.participation=percent(cast.length,bs.length); for(const b of cast){const peers=data.ballots.filter(x=>x.voteId===b.voteId&&x.party===b.party);const counts=Object.groupBy(peers,x=>x.choice);const majority=Object.entries(counts).sort((a,z)=>z[1].length-a[1].length)[0]?.[0];if(b.choice===majority)s.loyalty++}s.loyalty=percent(s.loyalty,cast.length);return s; }
function memberDetail(m){ if(!m)return notFound();const bs=data.ballots.filter(b=>b.mpId===m.id),voteIds=new Set(bs.map(b=>b.voteId)),vs=data.votes.filter(v=>voteIds.has(v.id)).slice(0,12),sp=data.speeches.filter(s=>s.mpId===m.id).slice(0,10);return `<div class="page">${header(titleFor(m.party),memberName(m),'Edustajan toiminta seuranta-ajanjaksolla.')}<div class="detail-grid"><div><h2>Viimeisimmät äänet</h2>${table(['Päivä','Asia','Tulos'],voteRows(vs))}<section class="section"><h2>Puheenvuorot</h2>${speechList(sp)}</section></div><aside class="aside"><h3>Toimintaluvut</h3><dl><dt>Osallistuminen</dt><dd>${m.stats.participation}%</dd><div class="meter"><span style="width:${m.stats.participation}%"></span></div><dt>Ryhmälinjan mukaisesti</dt><dd>${m.stats.loyalty}%</dd><div class="meter"><span style="width:${m.stats.loyalty}%"></span></div><dt>Äänet</dt><dd>${m.stats.yes} jaa · ${m.stats.no} ei · ${m.stats.abstain} tyhjää</dd><dt>Puheenvuorot</dt><dd>${m.stats.speeches}</dd></dl></aside></div></div>`; }
function parties(id){ if(id){const p=data.parties.find(x=>x.code===id);if(!p)return notFound();const ms=data.members.filter(m=>m.party===id).map(m=>({...m,stats:m.stats||memberStats(m.id)}));return `<div class="page">${header('Eduskuntaryhmä',titleFor(id),'Ryhmän osallistuminen, puheenvuorot ja jäsenten toiminta.')}<div class="detail-grid"><div>${table(['Edustaja','Osallistuminen','Ryhmälinja','Puheet'],memberRows(ms))}</div><aside class="aside"><h3>Ryhmäluvut</h3><dl><dt>Osallistuminen</dt><dd>${p.stats.participation}%</dd><dt>Kirjatut äänet</dt><dd>${p.stats.votes.toLocaleString('fi')}</dd><dt>Puheenvuorot</dt><dd>${p.stats.speeches.toLocaleString('fi')}</dd><dt>Edustajia aineistossa</dt><dd>${ms.length}</dd></dl></aside></div></div>`}return `<div class="page">${header('Vertailu','Puolueet','Vertaa eduskuntaryhmien äänestysosallistumista ja puheaktiivisuutta.')}<div class="cards">${data.parties.map(p=>`<a class="card" href="${href('parties',p.code)}"><span class="pill"><span class="party-dot"></span>${e(p.code.toUpperCase())}</span><h3 style="margin-top:1rem">${e(titleFor(p.code))}</h3><div class="big">${p.stats.participation}%</div><p>osallistuminen · ${p.stats.speeches} puheenvuoroa</p></a>`).join('')}</div></div>`; }
function speechList(items){return items.length?items.map(s=>`<article class="speech"><div class="date">${formatDate(s.date)} · <a href="${href('members',s.mpId)}">${e(memberName(s))}</a> · ${e(titleFor(s.party))}</div><h3>${e(s.agenda||'Täysistunnon puheenvuoro')}</h3>${s.text?`<blockquote>${e(s.text.slice(0,420))}${s.text.length>420?'…':''}</blockquote>`:'<p class="sub">Puheenvuoron tekstiä ei ole lähdedatassa.</p>'}</article>`).join(''):'<div class="empty">Ei puheenvuoroja.</div>'}
function speeches(){root.innerHTML=`<div class="page">${header('Täysistunnot','Puheenvuorot','Kansanedustajien puheenvuorot ja niihin liittyvät päiväjärjestysasiat.')}<div class="filters"><input data-filter placeholder="Hae puhujalla tai aiheella…"></div><div data-list>${speechList(data.speeches.slice(0,250))}</div></div>`;const input=$('[data-filter]');input.oninput=()=>{const hits=filterItems(data.speeches,input.value,['firstName','lastName','party','agenda','text']).slice(0,250);$('[data-list]').innerHTML=speechList(hits)}}
function legislation(id){ if(id){const l=data.legislation.find(x=>x.id===id);if(!l)return notFound();const vs=data.votes.filter(v=>l.voteIds.includes(v.id));return `<div class="page">${header(l.document,l.title,'Lakiasian äänestykset ja muutosehdotukset.')}<div class="detail-grid"><div>${table(['Päivä','Äänestys','Tulos'],voteRows(vs))}</div><aside class="aside"><h3>Asian eteneminen</h3><dl><dt>Vaiheet</dt><dd>${l.stages.map(e).join('<br>')||'—'}</dd><dt>Äänestykset</dt><dd>${l.voteIds.length}</dd><dt>Muutosehdotukset</dt><dd>${l.amendmentCount}</dd><dt>Virallinen asia</dt><dd><a href="${e(l.url)}" target="_blank">Avaa Eduskunnassa ↗</a></dd></dl></aside></div></div>`}const render=items=>items.map(l=>`<tr><td><a class="row-link" href="${href('legislation',l.id)}">${e(l.document)}</a><span class="sub">${e(l.title)}</span></td><td>${l.stages.map(x=>`<span class="pill">${e(x)}</span>`).join(' ')}</td><td>${l.voteIds.length}</td><td>${l.amendmentCount}</td></tr>`).join('');root.innerHTML=listPage('legislation','Lakiasiat','Hallituksen esitykset ja muut valtiopäiväasiat yhdistettynä äänestyksiin ja muutosehdotuksiin.',data.legislation,['Asia','Käsittelyvaiheet','Äänestykset','Muutokset'],render,'Hae asiakirjatunnuksella tai aiheella…');bindFilter(data.legislation,['document','title','stages'],['Asia','Käsittelyvaiheet','Äänestykset','Muutokset'],render);}
function sessions(id){if(id){const session=data.sessions.find(s=>s.id===id);if(!session)return notFound();const ids=new Set(session.voteIds);return `<div class="page">${header('Täysistunto',session.title,formatDate(session.date))}${table(['Päivä','Asia','Tulos'],voteRows(data.votes.filter(v=>ids.has(v.id))))}</div>`}return `<div class="page">${header('Täysistunnot','Istunnot','Istunnot ja niiden nimetyt äänestykset.')}<div class="cards">${data.sessions.map(s=>`<a class="card" href="${href('sessions',s.id)}"><div class="date">${formatDate(s.date)}</div><h3 style="margin-top:.7rem">${e(s.title)}</h3><div class="big">${s.voteIds.length}</div><p>äänestystä</p></a>`).join('')}</div></div>`}
function about(){return `<div class="page">${header('Avoin demokratia','Tietoa palvelusta')}<div class="detail-grid"><div><h2>Mitä palvelu tekee?</h2><p class="lead">Eduskunta-vahti järjestää Eduskunnan avoimen datan helposti selattavaan muotoon. Se näyttää nimetyt äänestykset, edustajien äänet, puheenvuorot sekä valtiopäiväasioihin liittyvät muutosehdotukset 2.4.2023 alkaen.</p><h2 class="section">Tulkinta</h2><p>Osallistuminen tarkoittaa muiden kuin poissa-äänten osuutta kaikista edustajalle kirjatuista äänistä. Ryhmälinja kertoo, kuinka usein edustajan ääni vastasi hänen ryhmänsä yleisintä ääntä kyseisessä äänestyksessä. Luvut eivät yksin mittaa työn laatua.</p></div><aside class="aside"><h3>Lähde ja vastuu</h3><p>Data: Eduskunnan avoin data. Palvelu on epävirallinen ja lähdetiedoissa voi olla puutteita tai viiveitä.</p><a href="https://avoindata.eduskunta.fi/swagger/apidocs.html" target="_blank">API-dokumentaatio ↗</a></aside></div></div>`}
function notFound(){return `<div class="page">${header('404','Sivua ei löytynyt')}<p><a href="#/overview">Palaa yleiskuvaan →</a></p></div>`}
function bindFilter(items,fields,heads,render){const input=$('[data-filter]');input.oninput=()=>{$('[data-list]').innerHTML=table(heads,render(filterItems(items,input.value,fields).slice(0,500)))}}
function render(){const r=routeFromHash(location.hash);document.querySelectorAll('.nav a').forEach(a=>a.classList.toggle('active',a.dataset.page===r.page));let html;if(r.page==='overview')html=overview();else if(r.page==='votes')html=votes(r.id);else if(r.page==='members')html=members(r.id);else if(r.page==='parties')html=parties(r.id);else if(r.page==='speeches')html=speeches();else if(r.page==='legislation')html=legislation(r.id);else if(r.page==='sessions')html=sessions(r.id);else if(r.page==='about')html=about();else html=notFound();if(typeof html==='string')root.innerHTML=html;window.scrollTo(0,0)}
function setupSearch(){const dialog=$('.search-dialog'),input=$('#global-search'),out=$('.search-results');$('.search-button').onclick=()=>{dialog.showModal();input.focus()};document.addEventListener('keydown',ev=>{if((ev.metaKey||ev.ctrlKey)&&ev.key.toLowerCase()==='k'){ev.preventDefault();dialog.showModal();input.focus()}if(ev.key==='Escape'&&dialog.open)dialog.close()});input.oninput=()=>{const q=input.value;const hits=[...filterItems(data.members,q,['firstName','lastName','party']).slice(0,5).map(x=>({label:memberName(x),sub:titleFor(x.party),url:href('members',x.id)})),...filterItems(data.votes,q,['title','question','document']).slice(0,5).map(x=>({label:x.title,sub:x.document,url:href('votes',x.id)})),...filterItems(data.legislation,q,['title','document']).slice(0,5).map(x=>({label:x.document,sub:x.title,url:href('legislation',x.id)}))];out.innerHTML=hits.map(x=>`<a class="search-hit" href="${x.url}" onclick="this.closest('dialog').close()"><strong>${e(x.label)}</strong><span class="sub">${e(x.sub)}</span></a>`).join('')||'<div class="empty">Ei osumia.</div>'}}
async function boot(){try{const response=await fetch('./data/parliament.json');if(!response.ok)throw new Error(`HTTP ${response.status}`);data=await response.json();data.ballots=hydrateBallots(data.ballots||[],data.members||[]);window.addEventListener('hashchange',render);$('.menu-button').onclick=()=>{const nav=$('.nav'),open=nav.classList.toggle('open');$('.menu-button').setAttribute('aria-expanded',open)};$('.nav').onclick=()=>$('.nav').classList.remove('open');setupSearch();render()}catch(error){root.innerHTML=`<div class="page"><div class="empty"><h2>Dataa ei voitu ladata</h2><p>${e(error.message)}</p><p>Suorita ensin <code>npm run sync</code>.</p></div></div>`}}boot();
