import { filterItems, percent, routeFromHash, hydrateBallots, pageSlice, choiceLabel, formatDate, escapeHTML } from './app-utils.js';

const $ = selector => document.querySelector(selector);
const root = $('#content');
const e = escapeHTML;
let data;
let lang = localStorage.getItem('vahtikissa-lang') === 'sv' ? 'sv' : 'fi';
const state = { votes: 1, speeches: 1, memberVotes: 1, memberSpeeches: 1 };
const PAGE = { votes: 50, speeches: 40, memberVotes: 30, memberSpeeches: 20 };
const partyNames = {
  kok:{fi:'Kansallinen Kokoomus',sv:'Samlingspartiet'}, ps:{fi:'Perussuomalaiset',sv:'Sannfinländarna'}, sd:{fi:'Suomen Sosialidemokraattinen Puolue',sv:'Finlands Socialdemokratiska Parti'}, kesk:{fi:'Suomen Keskusta',sv:'Centern i Finland'}, vihr:{fi:'Vihreä liitto',sv:'Gröna förbundet'}, vas:{fi:'Vasemmistoliitto',sv:'Vänsterförbundet'}, r:{fi:'Ruotsalainen kansanpuolue',sv:'Svenska folkpartiet'}, kd:{fi:'Suomen Kristillisdemokraatit',sv:'Kristdemokraterna i Finland'}, liik:{fi:'Liike Nyt',sv:'Rörelse Nu'}, sit:{fi:'Sitoutumaton',sv:'Obunden'}
};
const copy = {
  fi:{overview:'Yleiskuva',sessions:'Istunnot',votes:'Äänestykset',members:'Kansanedustajat',parties:'Puolueet',speeches:'Puheet',legislation:'Lakiasiat',search:'Hae',menu:'Valikko',loading:'Ladataan eduskunnan avointa dataa…',updated:'Päivitetty',day:'Päivä',matter:'Asia',result:'Tulos',yes:'jaa',no:'ei',abstain:'tyhjää',absent:'poissa',showMore:'Näytä lisää',showAll:'Näytä kaikki',latestVotes:'Uusimmat äänestykset',parliament:'Suomen eduskunta · avoin data',hero:'Miten sinun edustajasi toimii?',heroLead:'Seuraa äänestyksiä, puheenvuoroja, ryhmälinjoja ja lakiasioiden etenemistä 2.4.2023 alkaen.',voteRecords:'yksittäistä kansanedustajan äänimerkintää seurannassa',participation:'Osallistuminen',partyLine:'Ryhmälinja',recordedVotes:'kirjattua ääntä',speechTurns:'puheenvuoroa',vote:'Äänestys',background:'Taustatiedot',stage:'Käsittelyvaihe',officialMatter:'Valtiopäiväasia',minutes:'Pöytäkirja',officialVote:'Virallinen äänestystieto',openOfficial:'Avaa Eduskunnan lähteessä ↗',votesByParty:'Äänet puolueittain',recentVotes:'Äänestykset',mpSpeeches:'Puheenvuorot',mpActivity:'Edustajan toiminta seuranta-ajanjaksolla.',howVoted:'Äänesti',allVotes:'Kaikki nimetyt täysistuntoäänestykset huhtikuusta 2023 alkaen.',allSpeeches:'Kansanedustajien puheenvuorot ja niihin liittyvät päiväjärjestysasiat.',allLaws:'Valtiopäiväasiat yhdistettynä äänestyksiin ja muutosehdotuksiin.',searchVotes:'Hae aiheella tai asiakirjatunnuksella…',searchSpeeches:'Hae puhujalla tai aiheella…',searchMembers:'Hae nimellä tai puolueella…',searchLaws:'Hae asiakirjatunnuksella tai aiheella…',noData:'Ei tietoja.',independent:'Riippumaton avoimen datan palvelu. Ei ole Eduskunnan virallinen palvelu.',about:'Tietoa palvelusta',data:'Data'},
  sv:{overview:'Översikt',sessions:'Plenum',votes:'Omröstningar',members:'Riksdagsledamöter',parties:'Partier',speeches:'Anföranden',legislation:'Riksdagsärenden',search:'Sök',menu:'Meny',loading:'Riksdagens öppna data laddas…',updated:'Uppdaterad',day:'Datum',matter:'Ärende',result:'Resultat',yes:'ja',no:'nej',abstain:'blankt',absent:'frånvarande',showMore:'Visa fler',showAll:'Visa alla',latestVotes:'Senaste omröstningarna',parliament:'Finlands riksdag · öppna data',hero:'Hur agerar din riksdagsledamot?',heroLead:'Följ omröstningar, anföranden, grupplinjer och riksdagsärenden sedan 2.4.2023.',voteRecords:'registrerade individuella riksdagsröster',participation:'Deltagande',partyLine:'Grupplinje',recordedVotes:'registrerade röster',speechTurns:'anföranden',vote:'Omröstning',background:'Bakgrundsuppgifter',stage:'Behandlingsskede',officialMatter:'Riksdagsärende',minutes:'Protokoll',officialVote:'Officiella omröstningsuppgifter',openOfficial:'Öppna i riksdagens källa ↗',votesByParty:'Röster per parti',recentVotes:'Omröstningar',mpSpeeches:'Anföranden',mpActivity:'Ledamotens verksamhet under uppföljningsperioden.',howVoted:'Röstade',allVotes:'Alla namnupprop i plenum sedan april 2023.',allSpeeches:'Riksdagsledamöternas anföranden och relaterade dagordningsärenden.',allLaws:'Riksdagsärenden kopplade till omröstningar och ändringsförslag.',searchVotes:'Sök på ämne eller dokumentbeteckning…',searchSpeeches:'Sök på talare eller ämne…',searchMembers:'Sök på namn eller parti…',searchLaws:'Sök på dokumentbeteckning eller ämne…',noData:'Inga uppgifter.',independent:'En oberoende tjänst baserad på öppna data. Inte en officiell riksdagstjänst.',about:'Om tjänsten',data:'Data'}
};
const t = key => copy[lang][key] || copy.fi[key] || key;
const titleFor = party => partyNames[party]?.[lang] || partyNames[party]?.fi || String(party || '').toUpperCase();
const href = (page,id) => `#/${page}${id ? `/${encodeURIComponent(id)}` : ''}`;
const choice = key => choiceLabel(key,lang);
const fmtDate = value => formatDate(value,lang==='sv'?'sv-FI':'fi-FI');

function applyChrome(){document.documentElement.lang=lang;document.title='Vahtikissa';$('.brand').setAttribute('aria-label',lang==='sv'?'Vahtikissas startsida':'Vahtikissan etusivu');document.querySelectorAll('.brand-mark').forEach(x=>x.textContent='VK');document.querySelectorAll('.brand > span:last-child').forEach(x=>x.innerHTML='Vahti<em>kissa</em>');const keys=['overview','sessions','votes','members','parties','speeches','legislation'];document.querySelectorAll('.nav a').forEach((a,i)=>a.textContent=t(keys[i]));$('.menu-button').textContent=t('menu');$('.search-button').childNodes[0].textContent=`${t('search')} `;$('.site-footer-note').textContent=t('independent');$('.footer-data').textContent=t('data');$('.footer-about').textContent=t('about');$('.language-button').textContent=lang==='fi'?'På svenska':'Suomeksi';}
function resultBar(v){const total=v.total||v.yes+v.no+v.abstain+v.absent||1;return `<div class="result" role="img" aria-label="${t('yes')} ${v.yes}, ${t('no')} ${v.no}, ${t('abstain')} ${v.abstain}, ${t('absent')} ${v.absent}"><span style="width:${percent(v.yes,total)}%"></span><span style="width:${percent(v.no,total)}%"></span><span style="width:${percent(v.abstain,total)}%"></span><span style="width:${percent(v.absent,total)}%"></span></div><div class="vote-numbers"><span><b>${v.yes}</b> ${t('yes')}</span><span><b>${v.no}</b> ${t('no')}</span><span>${v.abstain} ${t('abstain')}</span><span>${v.absent} ${t('absent')}</span></div>`}
function header(kicker,title,lead=''){return `<div class="page-head"><div><div class="eyebrow">${e(kicker)}</div><h1>${e(title)}</h1>${lead?`<p class="lead">${e(lead)}</p>`:''}</div><div class="updated">${t('updated')} ${fmtDate(data.metadata.generatedAt)}</div></div>`}
function voteText(v,key){return lang==='sv'&&(v[`${key}Sv`])||v[key]||''}
function voteRows(items,mpId=null){return items.map(v=>{const ballot=mpId?data.ballots.find(b=>b.voteId===v.id&&b.mpId===mpId):null;return `<tr><td class="date">${fmtDate(v.date)}</td><td><a class="row-link" href="${href('votes',v.id)}">${e(voteText(v,'title')||voteText(v,'question')||t('vote'))}</a><span class="sub">${e(voteText(v,'document')||`${t('vote')} ${v.number}`)}${v.isAmendment?' · '+(lang==='sv'?'Ändringsförslag':'Muutosehdotus'):''}</span>${ballot?`<span class="mp-choice"><strong>${t('howVoted')}:</strong> ${e(choice(ballot.choice))}</span>`:''}</td><td>${resultBar(v)}</td></tr>`}).join('')}
function memberName(m){return `${m.firstName||''} ${m.lastName||''}`.trim()||`${lang==='sv'?'Ledamot':'Edustaja'} ${m.id||m.mpId}`}
function table(head,body){return `<div class="table-wrap"><table><thead><tr>${head.map(h=>`<th>${e(h)}</th>`).join('')}</tr></thead><tbody>${body}</tbody></table></div>`}
function moreButton(key,total){const shown=state[key]*PAGE[key];return shown<total?`<div class="load-more"><button data-load-more="${key}">${t('showMore')} <span>(${Math.min(PAGE[key],total-shown)})</span></button><small>${Math.min(shown,total)} / ${total}</small></div>`:''}
function stats(){const c=data.metadata.counts;return `<div class="stat-strip"><div class="stat"><strong>${c.votes.toLocaleString(lang)}</strong><span>${t('votes').toLowerCase()}</span></div><div class="stat"><strong>${c.members}</strong><span>${t('members').toLowerCase()}</span></div><div class="stat"><strong>${c.speeches.toLocaleString(lang)}</strong><span>${t('speechTurns')}</span></div><div class="stat"><strong>${c.legislation.toLocaleString(lang)}</strong><span>${t('legislation').toLowerCase()}</span></div><div class="stat"><strong>${c.amendments.toLocaleString(lang)}</strong><span>${lang==='sv'?'ändringsförslag':'muutosehdotusta'}</span></div></div>`}
function memberRows(items){return items.map(m=>`<tr><td><span class="avatar">${e((m.firstName?.[0]||'')+(m.lastName?.[0]||''))}</span><a class="row-link" href="${href('members',m.id)}">${e(memberName(m))}</a><span class="sub"><span class="party-dot"></span>${e(titleFor(m.party))}</span></td><td>${m.stats?.participation??0}%<span class="sub">${m.stats?.votes??0} ${t('recordedVotes')}</span></td><td>${m.stats?.loyalty??0}%</td><td>${m.stats?.speeches??0}</td></tr>`).join('')}
function overview(){const latest=data.votes.slice(0,8);return `<div class="page"><section class="hero"><div><div class="eyebrow">${t('parliament')}</div><h1>${t('hero')}</h1><p class="lead">${t('heroLead')}</p></div><div class="hero-side"><strong>${data.metadata.counts.ballots.toLocaleString(lang)}</strong><span>${t('voteRecords')}</span></div></section>${stats()}<section class="section"><div class="section-head"><h2>${t('latestVotes')}</h2><a href="#/votes">${t('showAll')} →</a></div>${table([t('day'),t('matter'),t('result')],voteRows(latest))}</section><section class="section"><div class="section-head"><h2>${t('parties')}</h2><a href="#/parties">${t('showAll')} →</a></div><div class="cards">${data.parties.map(p=>`<a class="card" href="${href('parties',p.code)}"><span class="pill">${e(p.code.toUpperCase())}</span><div class="big">${p.stats.participation}%</div><p>${e(titleFor(p.code))}</p></a>`).join('')}</div></section></div>`}
function voteList(){let filtered=data.votes;root.innerHTML=`<div class="page">${header(t('parliament'),t('votes'),t('allVotes'))}<div class="filters"><input data-filter aria-label="${e(t('searchVotes'))}" placeholder="${e(t('searchVotes'))}"></div><div data-list>${table([t('day'),t('matter'),t('result')],voteRows(filtered.slice(0,state.votes*PAGE.votes)))}</div><div data-more>${moreButton('votes',filtered.length)}</div></div>`;const redraw=()=>{$('[data-list]').innerHTML=table([t('day'),t('matter'),t('result')],voteRows(filtered.slice(0,state.votes*PAGE.votes)));$('[data-more]').innerHTML=moreButton('votes',filtered.length);bindMore()};$('[data-filter]').oninput=ev=>{filtered=filterItems(data.votes,ev.target.value,['title','question','document']);state.votes=1;redraw()};bindMore()}
function voteDetail(id){const v=data.votes.find(x=>x.id===id);if(!v)return notFound();const ballots=data.ballots.filter(b=>b.voteId===id);const groups=Object.entries(groupBy(ballots,b=>b.party)).sort((a,b)=>b[1].length-a[1].length);return `<div class="page">${header(`${t('vote')} ${v.number} · ${fmtDate(v.date)}`,voteText(v,'title')||voteText(v,'question'))}<div class="detail-grid"><div><h2>${t('result')}</h2><div style="margin:1rem 0 2rem">${resultBar(v)}</div><p>${e(voteText(v,'question'))}</p>${voteText(v,'detail')?`<p class="lead">${e(voteText(v,'detail'))}</p>`:''}<section class="section"><h2>${t('votesByParty')}</h2><div class="cards" style="margin-top:1rem">${groups.map(([party,bs])=>{const c={yes:0,no:0,abstain:0,absent:0,total:bs.length};bs.forEach(b=>c[b.choice]=(c[b.choice]||0)+1);return `<div class="card"><strong>${e(titleFor(party))}</strong><div style="margin-top:1rem">${resultBar(c)}</div><ul class="ballot-list">${bs.map(b=>`<li><a href="${href('members',b.mpId)}">${e(memberName(b))}</a><span>${e(choice(b.choice))}</span></li>`).join('')}</ul></div>`}).join('')}</div></section></div><aside class="aside"><h3>${t('background')}</h3><dl><dt>${t('stage')}</dt><dd>${e(voteText(v,'stage')||'—')}</dd><dt>${t('officialMatter')}</dt><dd>${v.documentUrl?`<a href="${e(v.documentUrl)}" target="_blank" rel="noreferrer">${e(voteText(v,'document'))} ↗</a>`:e(voteText(v,'document')||'—')}</dd><dt>${t('minutes')}</dt><dd>${e(voteText(v,'minutes')||'—')}</dd><dt>${t('officialVote')}</dt><dd><a href="${e(v.resultUrl)}" target="_blank" rel="noreferrer">${t('openOfficial')}</a></dd><dt>${t('result')}</dt><dd>${v.yes} ${t('yes')} · ${v.no} ${t('no')} · ${v.abstain} ${t('abstain')} · ${v.absent} ${t('absent')}</dd></dl></aside></div></div>`}
function members(id){if(id)return memberDetail(data.members.find(m=>m.id===id));const renderList=items=>table([t('members'),t('participation'),t('partyLine'),t('speeches')],memberRows(items));root.innerHTML=`<div class="page">${header(t('parliament'),t('members'))}<div class="filters"><input data-filter aria-label="${e(t('searchMembers'))}" placeholder="${e(t('searchMembers'))}"></div><div data-list>${renderList(data.members)}</div></div>`;$('[data-filter]').oninput=ev=>{$('[data-list]').innerHTML=renderList(filterItems(data.members,ev.target.value,['firstName','lastName','party']))}}
let activeMemberId=null;
function memberDetail(m){if(!m)return notFound();activeMemberId=m.id;const bs=data.ballots.filter(b=>b.mpId===m.id),voteIds=new Set(bs.map(b=>b.voteId)),vs=data.votes.filter(v=>voteIds.has(v.id)),sp=data.speeches.filter(s=>s.mpId===m.id);const renderMember=()=>{root.innerHTML=`<div class="page">${header(titleFor(m.party),memberName(m),t('mpActivity'))}<div class="detail-grid"><div><h2>${t('recentVotes')} <span class="count">${vs.length}</span></h2><div data-member-votes>${table([t('day'),t('matter'),t('result')],voteRows(vs.slice(0,state.memberVotes*PAGE.memberVotes),m.id))}</div><div data-member-votes-more>${moreButton('memberVotes',vs.length)}</div><section class="section"><h2>${t('mpSpeeches')} <span class="count">${sp.length}</span></h2><div data-member-speeches>${speechList(sp.slice(0,state.memberSpeeches*PAGE.memberSpeeches))}</div><div data-member-speeches-more>${moreButton('memberSpeeches',sp.length)}</div></section></div><aside class="aside"><h3>${lang==='sv'?'Aktivitetsmått':'Toimintaluvut'}</h3><dl><dt>${t('participation')}</dt><dd>${m.stats.participation}%</dd><div class="meter"><span style="width:${m.stats.participation}%"></span></div><dt>${t('partyLine')}</dt><dd>${m.stats.loyalty}%</dd><div class="meter"><span style="width:${m.stats.loyalty}%"></span></div><dt>${t('votes')}</dt><dd>${m.stats.yes} ${t('yes')} · ${m.stats.no} ${t('no')} · ${m.stats.abstain} ${t('abstain')}</dd><dt>${t('speeches')}</dt><dd>${m.stats.speeches}</dd></dl></aside></div></div>`;bindMore()};renderMember()}
function speechList(items){return items.length?items.map(s=>`<article class="speech"><div class="date">${fmtDate(s.date)} · <a href="${href('members',s.mpId)}">${e(memberName(s))}</a> · ${e(titleFor(s.party))}</div><h3>${e((lang==='sv'&&s.agendaSv)||s.agenda||t('speeches'))}</h3>${s.text?`<blockquote>${e(s.text)}</blockquote>`:`<p class="sub">${t('noData')}</p>`}${s.documents?.length?`<p class="source-links">${s.documents.map(d=>`<span>${e(d.label||d.name)}</span>`).join(' · ')}</p>`:''}</article>`).join(''):`<div class="empty">${t('noData')}</div>`}
function speeches(){let filtered=data.speeches;const redraw=()=>{root.innerHTML=`<div class="page">${header(t('parliament'),t('speeches'),t('allSpeeches'))}<div class="filters"><input data-filter aria-label="${e(t('searchSpeeches'))}" placeholder="${e(t('searchSpeeches'))}"></div><div data-list>${speechList(filtered.slice(0,state.speeches*PAGE.speeches))}</div><div data-more>${moreButton('speeches',filtered.length)}</div></div>`;$('[data-filter]').oninput=ev=>{filtered=filterItems(data.speeches,ev.target.value,['firstName','lastName','party','agenda','text']);state.speeches=1;redraw()};bindMore()};redraw()}
function legislation(id){if(id){const l=data.legislation.find(x=>x.id===id);if(!l)return notFound();const vs=data.votes.filter(v=>l.voteIds.includes(v.id));return `<div class="page">${header(l.document,l.title,t('allLaws'))}<div class="detail-grid"><div>${table([t('day'),t('vote'),t('result')],voteRows(vs))}</div><aside class="aside"><h3>${lang==='sv'?'Ärendets behandling':'Asian eteneminen'}</h3><dl><dt>${t('stage')}</dt><dd>${l.stages.map(e).join('<br>')||'—'}</dd><dt>${t('votes')}</dt><dd>${l.voteIds.length}</dd><dt>${lang==='sv'?'Ändringsförslag':'Muutosehdotukset'}</dt><dd>${l.amendmentCount}</dd><dt>${t('officialMatter')}</dt><dd><a href="${e(l.url)}" target="_blank" rel="noreferrer">${t('openOfficial')}</a></dd></dl></aside></div></div>`}const rows=data.legislation.map(l=>`<tr><td><a class="row-link" href="${href('legislation',l.id)}">${e(l.document)}</a><span class="sub">${e(l.title)}</span></td><td>${l.stages.map(x=>`<span class="pill">${e(x)}</span>`).join(' ')}</td><td>${l.voteIds.length}</td><td>${l.amendmentCount}</td></tr>`).join('');return `<div class="page">${header(t('parliament'),t('legislation'),t('allLaws'))}${table([t('matter'),t('stage'),t('votes'),lang==='sv'?'Ändringar':'Muutokset'],rows)}</div>`}
function parties(id){if(id){const p=data.parties.find(x=>x.code===id);if(!p)return notFound();const ms=data.members.filter(m=>m.party===id);return `<div class="page">${header(lang==='sv'?'Riksdagsgrupp':'Eduskuntaryhmä',titleFor(id))}<div class="detail-grid"><div>${table([t('members'),t('participation'),t('partyLine'),t('speeches')],memberRows(ms))}</div><aside class="aside"><h3>${lang==='sv'?'Gruppstatistik':'Ryhmäluvut'}</h3><dl><dt>${t('participation')}</dt><dd>${p.stats.participation}%</dd><dt>${t('votes')}</dt><dd>${p.stats.votes.toLocaleString(lang)}</dd><dt>${t('speeches')}</dt><dd>${p.stats.speeches.toLocaleString(lang)}</dd></dl></aside></div></div>`}return `<div class="page">${header(t('parliament'),t('parties'))}<div class="cards">${data.parties.map(p=>`<a class="card" href="${href('parties',p.code)}"><span class="pill">${e(p.code.toUpperCase())}</span><h3>${e(titleFor(p.code))}</h3><div class="big">${p.stats.participation}%</div></a>`).join('')}</div></div>`}
function sessions(id){if(id){const s=data.sessions.find(x=>x.id===id);if(!s)return notFound();const ids=new Set(s.voteIds);return `<div class="page">${header(t('sessions'),s.title,fmtDate(s.date))}${table([t('day'),t('matter'),t('result')],voteRows(data.votes.filter(v=>ids.has(v.id))))}</div>`}return `<div class="page">${header(t('parliament'),t('sessions'))}<div class="cards">${data.sessions.map(s=>`<a class="card" href="${href('sessions',s.id)}"><div class="date">${fmtDate(s.date)}</div><h3>${e(s.title)}</h3><div class="big">${s.voteIds.length}</div><p>${t('votes').toLowerCase()}</p></a>`).join('')}</div></div>`}
function about(){return `<div class="page">${header(t('parliament'),t('about'))}<div class="detail-grid"><div><p class="lead">${lang==='sv'?'Vahtikissa ordnar riksdagens öppna data i en lättöverskådlig form. Statistiken är beskrivande och mäter inte kvaliteten på det politiska arbetet.':'Vahtikissa järjestää Eduskunnan avoimen datan helposti selattavaan muotoon. Tilastot ovat kuvailevia eivätkä mittaa poliittisen työn laatua.'}</p></div><aside class="aside"><a href="https://api.eduskunta.fi/" target="_blank" rel="noreferrer">${t('openOfficial')}</a></aside></div></div>`}
function notFound(){return `<div class="page">${header('404',lang==='sv'?'Sidan hittades inte':'Sivua ei löytynyt')}</div>`}
function groupBy(items,key){return items.reduce((out,item)=>((out[key(item)]||=[]).push(item),out),{})}
function bindMore(){document.querySelectorAll('[data-load-more]').forEach(button=>button.onclick=()=>{const key=button.dataset.loadMore;state[key]++;if(key==='votes')voteList();else if(key==='speeches')speeches();else if((key==='memberVotes'||key==='memberSpeeches')&&activeMemberId)memberDetail(data.members.find(m=>m.id===activeMemberId));else render()})}
function render(){const r=routeFromHash(location.hash);document.querySelectorAll('.nav a').forEach(a=>a.classList.toggle('active',a.dataset.page===r.page));let html;if(r.page==='overview')html=overview();else if(r.page==='votes')html=r.id?voteDetail(r.id):null;else if(r.page==='members')html=members(r.id);else if(r.page==='parties')html=parties(r.id);else if(r.page==='speeches')html=null;else if(r.page==='legislation')html=legislation(r.id);else if(r.page==='sessions')html=sessions(r.id);else if(r.page==='about')html=about();else html=notFound();if(r.page==='votes'&&!r.id)voteList();else if(r.page==='speeches')speeches();else if(typeof html==='string')root.innerHTML=html;window.scrollTo(0,0)}
function setup(){applyChrome();$('.language-button').onclick=()=>{lang=lang==='fi'?'sv':'fi';localStorage.setItem('vahtikissa-lang',lang);applyChrome();render()};$('.menu-button').onclick=()=>{const open=$('.nav').classList.toggle('open');$('.menu-button').setAttribute('aria-expanded',open)};$('.search-button').onclick=()=>$('.search-dialog').showModal();window.addEventListener('hashchange',render)}
async function boot(){try{const response=await fetch('./data/parliament.json');if(!response.ok)throw new Error(`HTTP ${response.status}`);data=await response.json();data.ballots=hydrateBallots(data.ballots||[],data.members||[]);setup();render()}catch(error){root.innerHTML=`<div class="page"><div class="empty"><h2>${e(error.message)}</h2></div></div>`}}boot();
